GET http://localhost:8000/threads

###
POST http://localhost:8000/threads
Content-Type: application/json

{
  "title": "timestamp",
  "description": "test5"
}

###
GET http://localhost:8000/threads/640cd7402a9843478fd6b152