GET http://localhost:8000/threads

###
POST http://localhost:8000/threads
Content-Type: application/json

{
  "title": "timestamp",
  "description": "test5"
}

###
PATCH http://localhost:8000/threads/64004ad7a17203559dba773b
Content-Type: application/json

{
  "description": "patchのテスト3回目です"
}

###
GET http://localhost:8000/threads/630cd7402a9843478fd6b151

###
DELETE http://localhost:8000/threads/61004